name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: 
      - master

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      # Runs a single command using the runners shell
  buildPr:
    if: github.event_name == 'pull_request'
    uses: bielu/bielu.GithubActions.Templates/.github/workflows/ci.yml@main
    with:
      suffix: "pr"

  build:
    if: github.event_name == 'release'
    uses: bielu/bielu.GithubActions.Templates/.github/workflows/ci.yml@main
  
  buildBeta:
    if: github.event_name != 'pull_request' && github.event_name != 'release'
    uses: bielu/bielu.GithubActions.Templates/.github/workflows/ci.yml@main
    with:
      suffix: "beta"

  deploy:
    needs: [build,buildBeta]
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
    uses: bielu/bielu.GithubActions.Templates/.github/workflows/releaseNuget.yml@main
    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
